version: '3.3'

networks:
  default:
    driver: bridge

services:
  invoice_samurai:
    restart: always
    build:
      context: .
      target: invoice_samurai
    ports:
      - "5087:80"
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_ENVIRONMENT: "Production"
